apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: farmoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: farmoria-secrets
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: farmoria-secrets
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farmoria-secrets
                  key: MYSQL_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farmoria-secrets
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc