apiVersion: v1
kind: Secret
metadata:
  name: farmoria-secrets
  namespace: farmoria
type: Opaque
stringData:
  MYSQL_DATABASE: farmoria
  MYSQL_USER: farmoria_user
  MYSQL_PASSWORD: farmoria_pass
  MYSQL_ROOT_PASSWORD: root_pass